locale : "ko-KR"
title: Sinabro grow.
description: Hi, Hello.
author: Jinseop Sim
avatar: /profile.jpg
email: jjanggu1565@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: qwd.jpg
social:
  name: Jinseop Sim
  links:
    - https://github.com/Jinseop-Sim
    - https://www.instagram.com/_35yed
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
skin: daylight